// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Quintessentia.Data;

#nullable disable

namespace SpotifySummarizer.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251008043602_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SpotifySummarizer.Models.PodcastEpisode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BlobPath")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("CacheKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("DownloadDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<string>("OriginalUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.HasKey("Id");

                    b.HasIndex("CacheKey")
                        .IsUnique()
                        .HasDatabaseName("IX_PodcastEpisodes_CacheKey");

                    b.HasIndex("OriginalUrl")
                        .HasDatabaseName("IX_PodcastEpisodes_OriginalUrl");

                    b.ToTable("PodcastEpisodes", (string)null);
                });

            modelBuilder.Entity("SpotifySummarizer.Models.PodcastSummary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EpisodeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ProcessedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SummaryAudioBlobPath")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("SummaryTextBlobPath")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<int?>("SummaryWordCount")
                        .HasColumnType("int");

                    b.Property<string>("TranscriptBlobPath")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<int?>("TranscriptWordCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EpisodeId")
                        .IsUnique()
                        .HasDatabaseName("IX_PodcastSummaries_EpisodeId");

                    b.ToTable("PodcastSummaries", (string)null);
                });

            modelBuilder.Entity("SpotifySummarizer.Models.PodcastSummary", b =>
                {
                    b.HasOne("SpotifySummarizer.Models.PodcastEpisode", "Episode")
                        .WithOne("Summary")
                        .HasForeignKey("SpotifySummarizer.Models.PodcastSummary", "EpisodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Episode");
                });

            modelBuilder.Entity("SpotifySummarizer.Models.PodcastEpisode", b =>
                {
                    b.Navigation("Summary");
                });
#pragma warning restore 612, 618
        }
    }
}
